ldviewMongo:
  image: mongo
  restart: always

  ports:
    - 27017:27017

  volumes:
    - ./vol-mongo/:/data/db

ldviewFuseki:
  image: stain/jena-fuseki
  restart: always

  ports:
    - 3030:3030

  environment:
    - ADMIN_PASSWORD=tDj8UuDc6AAN2VG

  volumes:
    - ./vol-fuseki:/fuseki
