ldview-mongo:
  image: mongo

  ports:
    - 27001:27017

  volumes:
    - ./vol-mongo/:/data/db

ldview-fuseki:
  image: stain/jena-fuseki

  ports:
    - 3031:3030

  environment:
    - ADMIN_PASSWORD=tDj8UuDc6AAN2VG

  volumes:
    - ./vol-fuseki:/fuseki